### PR TITLE
ct_data_info: Encode/decode CS_IODESC datatype field.

### PR DESCRIPTION
**Pull request by ucko**
Split from #555.

### CODE REVIEW

**Comment by freddy77** [comment]
I think https://github.com/FreeTDS/freetds/commit/5f33559172c83972454270cc7c2a039d003168df took care of this issue.

**Comment by ucko** [comment]
Thanks, but what about the other direction?

**Comment by freddy77** [comment]
I look at the code and apparently, at the moment, it just stays there! Meaning you set into CT-Library and it's not used.
I suppose if someday it will be implemented we'll have to convert, if needed, to internal or server type.

**Comment by freddy77** [comment]
Can I close this PR?

**Comment by ucko** [comment]
OK, thanks.

**Pull request closed without merging**
