### PR TITLE
Use github actions

### PR DESCRIPTION
**Pull request by termim**
Add github actions to compile and test (on Linux) against Microsoft SQL server.

### CODE REVIEW

**Comment by freddy77** [comment]
It seems fine. Could you add `Signed-off-by` ?

Why did you exclude `ctlib` tests ?

I noted tests are run only for Linux. Is it not possible to have 2 containers using multiple OSes ?

**Comment by termim** [comment]
Added `Signed-off-by`.

I've commented out `ctlib` tests because if multiple runs are run in parallel (protocol versions * MSSQL version) `cancel.c` test hangs for 3 - 5 hours for some reason. When action is running with just one runner, then it runs fine.
Also I did not include ODBC tests as I could not properly configure it.

Unfortunately Windows and MacOS runners on Github do not support docker, so the only way to run tests on these platforms is to use some external source I guess.

**Comment by freddy77** [comment]
Merged

**Comment by freddy77** [comment]
The `cancel` behaviour looks weird, looking at the test it uses temporary tables, they should not conflict.

**Comment by freddy77** [comment]
Fixed and enabled both ctlib and ODBC.

**Pull request closed without merging**
