### PR TITLE
Added dbacolname

### PR DESCRIPTION
**Pull request by hankinsoft**
Added dbacolname so that column names can be retrieved for computed
columns.

### CODE REVIEW

**Comment by freddy77** [comment]
Patch looks good. I would change the API to return a const char * instead.
I'll add to master.

**Comment by hankinsoft** [comment]
I modified the result to be const char * as per your recommendation.

**Comment by freddy77** [comment]
Thanks. Merged which minor changes (mostly spaces).

**Comment by hankinsoft** [comment]
Thanks! Just to note, I think I added a second change regarding NTLMv2 to this that I should have probably split out. I didn't realize it would be added to my same pull request (not a bit github user).

**Comment by freddy77** [comment]
Merged last patch.
Thanks, sorry for the delay.

**Pull request closed without merging**
