### PR TITLE
Avoiding memory leak and null pointer dereference

### PR DESCRIPTION
**Pull request by klebertosantos**
This pull request aims to fix some memory leak and null pointer dereference.

[Memory Leak](https://cwe.mitre.org/data/definitions/401.html)
[Null pointer dereference](https://cwe.mitre.org/data/definitions/476.html)

### CODE REVIEW

**Comment by fziglio** [comment]
At least it would be good if the code compiled.

**Comment by klebertarcisio** [comment]
Hi @fziglio, all pull requests have a compilation error, would it be a problem with the configuration of continuous integration on github?

**Comment by klebertosantos** [comment]
Hi @fziglio, all pull requests have a compilation error, would it be a problem with the configuration of continuous integration on github?

**Comment by fziglio** [comment]
@klebertosantos, the issue is that your code is not even valid C code, not the CI.

**Comment by klebertosantos** [comment]
You are right! @fziglio  Now I made the correction by placing double quotes instead of single quotes. Thanks!

**Comment by freddy77** [comment]
Ok, better. Style, space after if. Error goes to error, not normal output. Library should not print on either standard or error output but return proper error.

**Comment by klebertosantos** [comment]
**Hi, @freddy77 Thanks for the feedback.** 
>Ok, better. Style, space after if.

Perfect, I can do it.

>Library should not print on either standard or error output but return proper error.

Could you tell me in which places should I not have the print?

>In a lot of other places the message is simply "out of memory".

Ok, I can replace "no memory to allocate" to "out of memory".

**Comment by fziglio** [comment]
> > Library should not print on either standard or error output but return proper error.
> 
> Could you tell me in which places should I not have the print?
> 
Sure,  `src/ctlib/ct.c`,  `src/dblib/dbpivot.c` and `src/tds/data.c`.

 On another subject, `src/tds/data.c` has a label you can probably reuse.

**Comment by klebertosantos** [comment]
Hi @fziglio, thanks for the feedback. I did some changes!

**Comment by freddy77** [comment]
About error on standard error I would replace `printf("out of memory");` to `fprintf(stderr, "out of memory\n");`

About `src/tds/data.c` I would add a label `error_memory` at the same line of `error_type` and jump to it instead. There's also another `tds_new0` in the same `tds_variant_get` function.

Could you squash the commits together? They are mainly fixes to other patches.

**Comment by freddy77** [comment]
@klebertosantos what about this commit https://github.com/FreeTDS/freetds/commit/b7483a5740f89fcbcb8cd8fa587132a8eaf84509 ? I updated a bit your ones

**Comment by klebertarcisio** [comment]
Hi @freddy77, sorry for the delay, i will update very soon.

**Comment by fziglio** [comment]
> Hi @freddy77, sorry for the delay, i will update very soon.

Aren't my changes fine?

**Comment by freddy77** [comment]
Merged

**Pull request closed without merging**
