### PR TITLE
tds_generic_put: Correct BCP 7.x new blob type handling

### PR DESCRIPTION
**Pull request by ucko**
... i.e., of VARCHAR(MAX) and the like.  Split from #555.

### CODE REVIEW

**Comment by freddy77** [comment]
That's... interesting! Tests passes with both this commit and without, so I suppose this path it's not really tested. Worth to write a test, and check TDS documentation!

**Comment by ucko** [comment]
An analogous patch to 1.4 *has* been helpful for some of my usage.  However, when I locally extended `ctlib`'s `long_binary` test to incorporate BCP, I found that it succeeded only *without* this change.  I'll take a closer look and get back to you.

**Comment by ucko** [comment]
AFAICT, whether this patch is helpful or harmful depends on runtime context TBD; I'll try to identify the relevant condition and adjust it accordingly.

**Comment by freddy77** [comment]
TDS protocol documentation seems to indicate PLP length is needed. Yes, it would be useful to extend a test to catch this. I vaguely remember this specific code (I wrote it) and it was kind of a bug in a specific server version, or a combination of server and protocol version. Wondering why I didn't write a test at that time.

**Comment by freddy77** [comment]
Added a test, see https://github.com/FreeTDS/freetds/commit/300611313f0e6d683bce436ac6b81df71265e4a2. Looks like it's working with current code, not with this patch applied.

**Comment by freddy77** [comment]
Could it be that this commit was here to fix an old bug handling empty strings?

**Comment by ucko** [comment]
Aha, the supporting logic for `blk_textxfer` in #558 doesn't account for possibly needing to send a final PLP length of zero.  I'll fix that instead.

**Comment by ucko** [comment]
Withdrawn in favor of #558.

**Pull request closed without merging**
