### PR TITLE
WIP: per-DBPROCESS query_timeout via setdbopt().

### PR DESCRIPTION
**Pull request by ramiro**
See http://marc.info/?l=freetds&m=126037476326260

Note: This isn't tested yet. Just trying to see if the approach is sound and hopefully get some feedback.

### CODE REVIEW

**Comment by freddy77** [comment]
This looks in line also with https://technet.microsoft.com/en-us/library/aa937147%28v=sql.80%29.aspx.
Just one comment: I don't think the "dblib option" comments are much helpful, the code is about dblib and functions about setting/clearing options.

I would also reuse the "i" variable instead of using a new "to".. or change to something more readable like "timeout" but the code is so short won't increase much readability.

**Comment by freddy77** [comment]
Also in the other patch there was a test for this setting. Quite long perhaps but could help (possibly in another commit).

**Comment by joshuahlang** [comment]
Adding the per-process timeouts using the dbsetopt is preferable to my approach as it is simpler to write backwards compatible code against it. Feel free to cherry-pick any test from my pull-request as needed.

Also, any chance this can go in for the 1.0 release?

**Comment by freddy77** [comment]
Idea and implementations looks good. I merged together yours, Joshua and some others in 4 commits.

All various CI are working like hell now!

Thanks.

**Comment by freddy77** [comment]
2016-05-04 0:29 GMT+01:00 joshuahlang <notifications@github.com>:

> Adding the per-process timeouts using the dbsetopt is preferable to my
> approach as it is simpler to write backwards compatible code against it.
> Feel free to cherry-pick any test from my pull-request as needed.
>
> Also, any chance this can go in for the 1.0 release?
>
>
Already in the branch!

Frediano

**Pull request closed without merging**
