### PR TITLE
Add release to Linux action

### PR DESCRIPTION
**Pull request by termim**
In Linux action create Github release when a tag starting with `v` is pushed.

### CODE REVIEW

**Comment by termim** [comment]
It is possible to rerun failed actions with `Re-run` button if the failure is intermittent.

**Comment by freddy77** [comment]
To be honest I would even remove `dist` job. There are packages at the official website, see www.freetds.org.

**Comment by termim** [comment]
OK, no problem. You can close the PR then.

**Comment by freddy77** [comment]
There are some difference why I prefer the ones from the website
- better controlled environment;
- user guide and source reference are built and packaged;
- more easy to understand which version is more recent having an incremental number.

**Comment by freddy77** [comment]
As discussed removed the distribution from Github actions. Closing this PR

**Pull request closed without merging**
